language: node_js
node_js:
    - "0.10"
notifications:
    slack: bartr:moNL7Sen4nyyk0W6lWTiQIEv
install:
    - "npm install; sudo pip install awsebcli; sudo pip install awscli;"
after_success:
    - "if [ ${TRAVIS_BRANCH} == master ]; then
           eb init;
           eb deploy barter;
       fi"
    - "if [[ -n $(git diff HEAD~1 HEAD doc/swagger.json) ]]; then
           aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID};
           aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY};
           aws configure set default.region ${AWS_DEFAULT_REGION};
           aws s3 cp doc/swagger.json s3://cs130barter --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers;
       fi"
