language: node_js
node_js:
    - "0.10"
notifications:
    slack: bartr:moNL7Sen4nyyk0W6lWTiQIEv
install:
    - "sudo pip install awsebcli"
after_success:
    - "if [ ${TRAVIS_BRANCH} == master ]; then
           eb init;
           eb deploy barter;
       fi"
